#genome assembly using hifiasm
hifiasm -o S1979 -t 40 --hg-size 1.2g ../all.ccs.fasta.gz --ul all.ONTultra_NanoFilt.fastq.gz --ul-cut 50000 --h1 S1979_HiC.clean_1.fq.gz --h2 S1979_HiC.clean_2.fq.gz
#gfa to fasta
awk '/^S/{print ">"$2;print $3}' S1979.hic.p_ctg.gfa >S1979.hic.p_ctg.fa

#genome assembly using NextDenovo
nextDenovo run.cfg
#polish contigs
nextPolish run.cfg

#Comparative analysis of contigs generated by hifiasm and NextDenovo.
/pub/pipeline/software/mummer-4.0.0/bin/nucmer -D 5 --mum -p HiFivsNextDenvo.contig -t 20 HiFi.contig.fa NextDenovo.contig.fa
/pub/pipeline/software/mummer-4.0.0/bin/delta-filter -i 95 -l 2000 -q -1 HiFivsNextDenvo.contig.delta >HiFivsNextDenvo.contig.filter2K.delta
/pub/pipeline/software/mummer-4.0.0/bin/show-coords -rcl HiFivsNextDenvo.contig.filter2K.delta >HiFivsNextDenvo.contig.filter2K.coords
